### ISSUE TITLE
Kacie: Add assets for team presentation

### ISSUE THREAD

**Issue by IascAtBrock** [IascAtBrock/IASC-2P02-TeamPresentations#5]
This is an individual issue assigned to you alone. Mark it as resolved once you have finished uploading your assets to your team's shared fork.

**Comment by Kacie-deWit** [comment]
Worked on the theoretical part of the 

 Jazz link helps us see the information in a new light.  As Drucker explained, this can show us a broader spectrum of information we are given. 

Instead of showing us just a timeline on a mathematical scale, Linked Jazz gives us different ways for us to view this type of information. 

Whether you are coming from a linguistic point of view or if you are looking at this through a psychological lense. Showing us how close someone may be to another person can help us better understand what, how and why there was a certain outcome in someone’s life. Being able to visibly show us these links can help us better take in the information we need.
